/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.UsuarioDAO;
import DTO.usuariosDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10
 */
public class formVIEW extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public formVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeuser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        senhauser = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        btnentrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(601, 420));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 110, 81, 29);

        nomeuser.setBackground(new java.awt.Color(0, 0, 0));
        nomeuser.setForeground(new java.awt.Color(255, 255, 255));
        nomeuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeuserActionPerformed(evt);
            }
        });
        jPanel1.add(nomeuser);
        nomeuser.setBounds(50, 180, 195, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMAIL");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 150, 40, 16);

        senhauser.setBackground(new java.awt.Color(0, 0, 0));
        senhauser.setForeground(new java.awt.Color(255, 255, 255));
        senhauser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(senhauser);
        senhauser.setBounds(50, 270, 195, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SENHA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 240, 50, 16);

        voltar.setBackground(new java.awt.Color(0, 0, 0));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/certo_1.png"))); // NOI18N
        voltar.setBorder(null);
        voltar.setBorderPainted(false);
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(10, 10, 75, 60);

        btnentrar.setText("Entrar");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnentrar);
        btnentrar.setBounds(110, 320, 72, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 420);

        setSize(new java.awt.Dimension(617, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        try{
            String nome, senha;

            nome = nomeuser.getText();
            senha = senhauser.getText();

            usuariosDTO objusuariosdto = new usuariosDTO();
            objusuariosdto.setNome(nome);
            objusuariosdto.setSenha(senha);

            UsuarioDAO objusuariodao = new UsuarioDAO();
            ResultSet rsusuariodao = objusuariodao.autenticacaoUsuario(objusuariosdto);

            if (rsusuariodao.next()) {
                //chamar tela que eu quero abrir
                AfterLoginVIEW objafterloginview = new AfterLoginVIEW();
                objafterloginview.setVisible(true);

                dispose();
            } else{
                // enviar msg dizendo incorretos
                JOptionPane.showMessageDialog(null, "Usuário ou senha errados");
            }

        }catch (SQLException erro){
            JOptionPane.showMessageDialog(null, "formVIEW" + erro);
        }

    }//GEN-LAST:event_btnentrarActionPerformed

    private void nomeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeuserActionPerformed

    }//GEN-LAST:event_nomeuserActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        PrincipalVIEW tela = new PrincipalVIEW();//criando um objeto
         tela.setVisible(true);//tornando o objeto tela visÃ­vel(true)
         dispose();//Fechando a tela login
        
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeuser;
    private javax.swing.JPasswordField senhauser;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
