/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Windows 10
 */
public class PrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVIEW
     */
    public PrincipalVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HOME1 = new javax.swing.JButton();
        HOME = new javax.swing.JButton();
        LOGIN = new javax.swing.JButton();
        CADASTRO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(601, 420));
        getContentPane().setLayout(null);

        HOME1.setBackground(new java.awt.Color(0, 0, 0));
        HOME1.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        HOME1.setForeground(new java.awt.Color(255, 255, 255));
        HOME1.setText("SOBRE");
        HOME1.setBorder(null);
        HOME1.setBorderPainted(false);
        HOME1.setContentAreaFilled(false);
        HOME1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOME1ActionPerformed(evt);
            }
        });
        getContentPane().add(HOME1);
        HOME1.setBounds(450, 30, 38, 17);

        HOME.setBackground(new java.awt.Color(0, 0, 0));
        HOME.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        HOME.setForeground(new java.awt.Color(255, 255, 255));
        HOME.setText("HOME");
        HOME.setBorder(null);
        HOME.setBorderPainted(false);
        HOME.setContentAreaFilled(false);
        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });
        getContentPane().add(HOME);
        HOME.setBounds(380, 30, 36, 17);

        LOGIN.setBackground(new java.awt.Color(0, 0, 0));
        LOGIN.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        LOGIN.setText("LOGIN");
        LOGIN.setBorder(null);
        LOGIN.setBorderPainted(false);
        LOGIN.setContentAreaFilled(false);
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(LOGIN);
        LOGIN.setBounds(150, 30, 75, 17);

        CADASTRO.setBackground(new java.awt.Color(0, 0, 0));
        CADASTRO.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        CADASTRO.setForeground(new java.awt.Color(255, 204, 102));
        CADASTRO.setText("CADASTRO");
        CADASTRO.setToolTipText("");
        CADASTRO.setBorder(null);
        CADASTRO.setBorderPainted(false);
        CADASTRO.setContentAreaFilled(false);
        CADASTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTROActionPerformed(evt);
            }
        });
        getContentPane().add(CADASTRO);
        CADASTRO.setBounds(30, 30, 100, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icon_cybe.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 320, 90, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/astroneer.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 80, 120, 90);

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Em Astroneer, os jogadores devem ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 170, 210, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("encontrar formas de sobreviver  em um");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 190, 220, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("sistema solar isolado");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 210, 120, 16);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setForeground(new java.awt.Color(255, 204, 102));

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jButton1.setText("Jogue Grátis");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 240, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/foguete.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 60, 530, 350);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/asjnweofw.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 590, 369);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
        PrincipalVIEW tela = new PrincipalVIEW();//criando um objeto
         tela.setVisible(true);//tornando o objeto tela visÃ­vel(true)
         dispose();//Fechando a tela login
    }//GEN-LAST:event_HOMEActionPerformed

    private void CADASTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTROActionPerformed
         CadastroVIEW cadas = new CadastroVIEW();//criando um objeto
         cadas.setVisible(true);//tornando o objeto tela visÃ­vel(true)
         dispose();//Fechando a tela login
    }//GEN-LAST:event_CADASTROActionPerformed

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
        formVIEW login = new formVIEW();//criando um objeto
         login.setVisible(true);//tornando o objeto tela visÃ­vel(true)
         dispose();//Fechando a tela login
    }//GEN-LAST:event_LOGINActionPerformed

    private void HOME1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOME1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HOME1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CADASTRO;
    private javax.swing.JButton HOME;
    private javax.swing.JButton HOME1;
    private javax.swing.JButton LOGIN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
